#!/usr/bin/env bash
# Set up HAProxy

# Update package list
sudo apt-get update -y

# Install HAProxy
sudo apt-get install -y haproxy

# Check if HAProxy is installed
if ! command -v haproxy &> /dev/null; then
    echo "HAProxy installation failed. Exiting."
    exit 1
fi

# Set ownership of HAProxy configuration files
sudo chown "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo chown "$USER":"$USER" /etc/default/haproxy

# Enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOL
listen http-in
    bind *:80
    mode http
    balance roundrobin
    server web-01 54.89.136.45:80 check
    server web-02 18.207.233.210:80 check
EOL

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Check HAProxy status
sudo systemctl status haproxy
